apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    test: l4lb-rbs-load
  annotations:
    cloud.google.com/l4-rbs: enabled
spec:
  externalTrafficPolicy: {{.ExternalTrafficPolicy}}
  type: LoadBalancer
  selector:
    name: {{.DeploymentBaseName}}-{{.Index}}
  ports:
  - port: 80
    targetPort: 80
