apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: ilb-load
spec:
  replicas: {{.NumReplicas}}
  selector:
    matchLabels:
      name: {{.Name}}
  template:
    metadata:
      labels:
        group: ilb-load
        name: {{.Name}}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - {{.Name}}
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{.Name}}
        image: nginx
        ports:
        - containerPort: 8080
