apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  labels:
    size: {{.LBSizeLabel}}
  annotations:
    networking.gke.io/load-balancer-type: {{.LoadBalancerType}}
spec:
  externalTrafficPolicy: {{.ExternalTrafficPolicy}}
  type: LoadBalancer
  selector:
    name: {{.DeploymentBaseName}}-{{.Index}}
  ipFamilyPolicy: RequireDualStack
  ports:
  - port: 8080
    targetPort: 80
